models/Tareas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tareas".
 *
 * @property int $id_tarea
 * @property string $nombre
 * @property string $descripcion
 * @property string $categoria
 * @property string $prioridad
 * @property string $fecha_inicio
 * @property string $fecha_fin
 * @property string $propietario
 *
 * @property Usuarios $propietario0
 */
class Tareas extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tareas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'categoria', 'prioridad', 'fecha_inicio', 'fecha_fin', 'propietario'], 'required'],
            [['fecha_inicio', 'fecha_fin'], 'safe'],
            [['nombre', 'descripcion', 'categoria', 'prioridad', 'propietario'], 'string', 'max' => 255],
            [['propietario'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['propietario' => 'username']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_tarea' => 'Id Tarea',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'categoria' => 'Categoria',
            'prioridad' => 'Prioridad',
            'fecha_inicio' => 'Fecha Inicio',
            'fecha_fin' => 'Fecha Fin',
            'propietario' => 'Propietario',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropietario0()
    {
        return $this->hasOne(User::className(), ['username' => 'propietario']);
    }

    /**
     * @inheritdoc
     * @return TareasQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TareasQuery(get_called_class());
    }
}

controllers/TareasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tareas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * TareasController implements the CRUD actions for Tareas model.
 */
class TareasController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tareas models.
     * @return mixed
     */
    public function actionIndex($username)
    {
        
        $dataProvider = new ActiveDataProvider([
            'query' => Tareas::find()->where(['propietario'=>$username]),
        ]);
        
        
                
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

   
     public function actionListar()
    {
        
        $dataProvider = new ActiveDataProvider([
            'query' => Tareas::find(),
            ]);
        
      
        return $this->render('listar', [
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Displays a single Tareas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tareas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tareas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'username' => $model->propietario]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tareas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id); 

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'username' => $model->propietario]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tareas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        
        $this->findModel($id)->delete();
        
        return $this->redirect(['index', 'username'=>Yii::$app->user->identity->username]);
    }

    /**
     * Finds the Tareas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tareas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tareas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/tareas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Tareas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tareas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'categoria')->textInput(['maxlength' => true]) ?>

    <?=
            $form->field($model, 'prioridad')
            ->dropDownList([
                'BAJA' => 'BAJA', 'MEDIA' => 'MEDIA', 'ALTA' => 'ALTA', 'URGENTE' => 'URGENTE'
                    ], ['prompt' => 'Selecciona una Prioridad']);
    ?>
    <div class="row">
        <div class="col-lg-offset-2 col-lg-5">
    <?=
    $form->field($model, 'fecha_inicio')->widget(
            DatePicker::className(), [
        // inline too, not bad
        'inline' => true,
                'language'=>'es',
        'dateFormat' => 'yyyy-MM-dd'
    ]);
    ?>
            </div>
<div class="col-lg-5">
    <?=
    $form->field($model, 'fecha_fin')->textInput()->widget(DatePicker::className(), [
        'inline' => true,
        'dateFormat' => 'yyyy-MM-dd'
    ]);
    ?>
    </div>
       </div>
    <?= $form->field($model, 'propietario')->textInput(['value' => Yii::$app->user->identity->username, 'readonly' => true]) ?>


    <div class="form-group">
<?= Html::submitButton('GUARDAR', ['class' => 'btn btn-success']) ?>
    </div>

<?php ActiveForm::end(); ?>

</div>

views/tareas/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tareas */

$this->title = 'Crear Tareas';
$this->params['breadcrumbs'][] = ['label' => 'Tareas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tareas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tareas/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use sjaakp\gcharts\ColumnChart;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

if(Yii::$app->user->identity->admin){
    echo " <h1 class='text-center'>BIENVENIDO ADMINISTRADOR </h1>";
}
else{
$this->title = 'Mis Tareas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tareas-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Tareas', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'id_tarea',
            [

                'attribute' => 'nombre',
                'format' => 'html',
                'value' => function($model) {
                    return Html::a($model->nombre, ['tareas/view', 'id' => $model->id_tarea]);
                }
                    ],
            'descripcion',
            'categoria',
            'prioridad',
            'fecha_inicio',
            'fecha_fin',
            //'propietario',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); 
}?>
</div>

<div>
        <?= ColumnChart::widget([
    'height' => '400px',
    'dataProvider' => $dataProvider,
    'columns' => [
        'nombre:string',
        'fecha_inicio:date',
        'fecha_fin:date'
    ],
    'options' => [
        'title' => 'ESTADO de las TAREAS',
        
    ],
]) ?>
    </div> 

views/tareas/listar.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use sjaakp\gcharts\PieChart;
use sjaakp\gcharts\ColumnChart;
use sjaakp\timeline\Timeline;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Mis Tareas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tareas-index">

    <h1><?= Html::encode($this->title) ?></h1>


    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'id_tarea',
            [
                'attribute' => 'nombre',
                'format' => 'html',
                'value' => function($model) {
                    return Html::a($model->nombre, ['tareas/view', 'id' => $model->id_tarea]);
                }
            ],
            'descripcion',
            'categoria',
            'prioridad',
            'fecha_inicio',
            'fecha_fin',
            'propietario',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>

views/tareas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tareas */

$this->title = 'Modificar la Tarea número ' . $model->id_tarea;
$this->params['breadcrumbs'][] = ['label' => 'Tareas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_tarea, 'url' => ['view', 'id' => $model->id_tarea]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tareas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tareas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Tareas */

$this->title = $model->id_tarea;
$this->params['breadcrumbs'][] = ['label' => 'Tareas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tareas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Modificar', ['update', 'id' => $model->id_tarea], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Borrar', ['delete', 'id' => $model->id_tarea], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_tarea',
            'nombre',
            'descripcion',
            'categoria',
            'prioridad',
            'fecha_inicio',
            'fecha_fin',
            'propietario',
        ],
    ]) ?>

</div>